# Generated by Django 4.2.1 on 2023-05-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todoitem_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='task_priority',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
